### ISSUE TITLE
Link to thesis is dead

### ISSUE THREAD

**Issue by cbcoutinho** [wyldckat/perturbU#2]
Hi @wyldckat,

Thanks for hosting this repository. I noticed when looking through the README that the link to Eugene's thesis is dead. This looks like an appropriate replacement: http://powerlab.fsb.hr/ped/kturbo/OpenFOAM/docs/EugeneDeVilliersPhD2006.pdf

Cheers

**Comment by wyldckat** [comment]
Hi @cbcoutinho,

Many thanks! I've corrected this now on the README.md file, in the commit mentioned above.

I will look into the wiki page next, but I'll close this issue now, since it's fixed here in the repository ;)

Best regards,
Bruno
