### ISSUE TITLE
Error while compiling with OF v 1906

### ISSUE THREAD

**Issue by chandukec** [wyldckat/perturbU#4]
Hi, 
Many thanks for this wonderful utility, I am trying to run a LES of channel flow at Re_\tau = 180, but unable to get the turbulence, meanwhile inside the CFD online discussion forum found your utility. When I tried to install/build it with OpenFOAM v1906, using wmake, I am getting the following errors:
```
/home/frankel/OpenFOAM/OpenFOAM-v1906/src/finiteVolume/lnInclude/cyclicAMIFvPatch.H:41:10: fatal error: cyclicAMILduInterface.H: No such file or directory
   41 | #include "cyclicAMILduInterface.H"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/home/frankel/OpenFOAM/OpenFOAM-v1906/wmake/rules/General/transform:35: Make/linux64GccDPInt32Opt/perturbU.o] Error 1
```
Any comment/suggestion would be welcomed, many thanks in advance.

**Comment by wyldckat** [comment]
Quick answer: It looks like you checked out some older version branch than OF4x and/or did not follow the instructions on the wiki: https://openfoamwiki.net/index.php/Contrib/perturbU

That said, OpenFOAM.com v1906 was not yet supported, nor OpenFOAM.org 5 and newer, for which I've now added branches for.

Run the following commands, from within the folder where you have `perturbU`:

```
git pull
git checkout OFcom1906
wclean all
wmake all
```

Hopefully it now builds and runs well.

**Comment by chandukec** [comment]
Many thanks for your help and reply, but still it is throwing an error which says:
```
error: ‘class Foam::Random’ has no member named ‘scalarNormal’
  173 |         scalar deviation=1.0 + 0.2*perturbation.scalarNormal();
```
Could you please further help? Many thanks in advance.

**Comment by wyldckat** [comment]
Sorry about that, it should be fixed now... run these commands:

```
git pull
wclean all
wmake all
```

**Comment by chandukec** [comment]
Many thanks, it worked now. Although not related -- I have a converged RANS result for channel flow that I wanted to impose for the LES sims, thus I have the following queries:
1. I should place the perturbUDict inside the system folder and change the following: Retau 180; (assume based on channel half width and utau), rest quantities unchanged --assuming streamwise direction is x, and spanwise is z.
2. First run this utility to see the changes in the time folder of 1000 ?
Sorry for asking irrelevant questions in this github repository.

**Comment by wyldckat** [comment]
Quick answers:
1. I never used this myself, so the questions on how to use the dictionary itself should be asked on the relevant forum thread.
2. File `system/controlDict` and modify `startFrom` to start from `startTime`.

**Comment by chandukec** [comment]
Sorry for bothering you again, but while running it by placing it inside the constant folder, it is giving errors:
```
--> FOAM FATAL IO ERROR: 
Wrong token type - expected word, found on line 22: double 2e-05

file: /home/frankel/OpenFOAM/frankel-v2112/run/ABI_2022/v24_channel_re180_pressure_driven_bigdomain/LES_v3/constant/transportProperties.nu at line 22.

    From function Foam::Istream& Foam::operator>>(Foam::Istream&, Foam::word&)
    in file primitives/strings/word/wordIO.C at line 77.
```

**Comment by chandukec** [comment]
Never mind as per your suggestion, I looked at the relevant forum and found the solution using:
https://www.cfd-online.com/Forums/openfoam-solving/59602-perturbu-2.html
Anyways million of tons, thanks, highly appreciate your timely help.
